"""Shared configuration values for the runtime and starter content."""

from __future__ import annotations

from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = PACKAGE_ROOT.parent
PROJECTS_DIR = PROJECT_ROOT / "projects"
DATA_DIR = PACKAGE_ROOT / "data"
AREAS_DIR = DATA_DIR / "areas"
ENTITIES_DIR = DATA_DIR / "entities"
ASSETS_DIR = DATA_DIR / "assets"
TILES_DIR = ASSETS_DIR / "tiles"
FONTS_DIR = DATA_DIR / "fonts"
SETTINGS_DIR = PROJECT_ROOT / "settings"
LAUNCHER_STATE_PATH = SETTINGS_DIR / "launcher_state.json"
LOGS_DIR = PROJECT_ROOT / "logs"
ERROR_LOG_PATH = LOGS_DIR / "error.log"
SAVES_DIR = PROJECT_ROOT / "saves"

WINDOW_TITLE = "Python Dungeon Engine"
INTERNAL_WIDTH = 320
INTERNAL_HEIGHT = 240
SCALE = 3
MIN_SCALE = 1
MAX_SCALE = 8
FPS = 60
FIXED_TIMESTEP_SECONDS = 1.0 / FPS
DEFAULT_TILE_SIZE = 16
MOVE_DURATION_SECONDS = 0.14
PIXEL_ART_MODE = True
DEFAULT_UI_FONT_ID = "pixelbet"
DEFAULT_DIALOGUE_FONT_ID = "pixelbet"
COMMAND_RUNTIME_MAX_SETTLE_PASSES = 128
COMMAND_RUNTIME_MAX_IMMEDIATE_COMMANDS_PER_SETTLE = 8192
COMMAND_RUNTIME_LOG_SETTLE_USAGE_PEAKS = False
COMMAND_RUNTIME_SETTLE_WARNING_RATIO = 0.75

COLOR_BACKGROUND = (18, 20, 26)
COLOR_FLOOR = (74, 85, 104)
COLOR_WALL = (41, 48, 62)
COLOR_GRID_ACCENT = (108, 122, 143)
COLOR_TEXT = (238, 242, 248)
